#build stage
FROM golang:alpine AS build
WORKDIR /usr/src/app
COPY go.mod go.sum main.go ./
RUN go mod download && go mod verify
RUN go build -o app .

#final stage
FROM golang:alpine
WORKDIR /root/
COPY --from=build /usr/src/app ./
EXPOSE 9080
CMD ["./app"]
