FROM node:12-alpine AS build
RUN apk add yarn \
    && mkdir -p /app
COPY . /app
WORKDIR /app
RUN yarn install \
    && yarn build

# enable
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/env.sh /dockerentrypoint.d
COPY conf.d/default.conf /etc/nginx/conf.d
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]